### ISSUE TITLE
Saving Annotation collapses the bubble

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#118]
**On Chrome**
Steps:
1. Import test audio file. You get one bubble.
2. Click edit on the Annotation and edit the name.
3. Click save.

Your bubble gets squished to the right:
![image](https://user-images.githubusercontent.com/16720883/46442303-328c8a00-c737-11e8-90aa-26abfe399409.png)

**On Firefox**
Can't edit, so can't test it there.

**On Edge**
The bubble disappears altogether if you save.

**Comment by adam-digirati** [comment]
This issue is related to the discrepancies between time picker implementations in different browsers and operating systems. Technically it is a duplicate of #117. I won't close it until we fix #117.
