### ISSUE TITLE
As a user, I want to be able to hear the section of music relating to the bubble I have selected so that I can form my annotation.

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#12]
**Acceptance criteria**
* [x] User can hear section of audio when a bubble is selected
* [ ] I can click a button to enable looping of the section of audio
* [ ] I can click the same button again to disable looping of the track

**Dev tasks**
* [ todo ]

**Comment by jwd** [comment]
User should be able to turn looping on/off. Default in Variations was not to loop.

**Comment by stephenwf** [comment]
@jwd I've updated the acceptance criteria to reflect that now
