### ISSUE TITLE
Undo option unavailable

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#120]
When adding bubbles, there is no way to undo an action. For instance, after clicking on Add to split a bubble, if I have the wrong bubble selected and want to undo that split, I can't.

The Undo option is also missing when one deletes a bubble.

**Comment by villedigirati** [comment]
Will need UX Design, and probably tweak the MVP solution for clearing annotations

**Comment by villedigirati** [comment]
This issue is now moved to the ticket https://github.com/digirati-co-uk/timeliner/issues/201

Closing this issue
