### ISSUE TITLE
Bubble height algorithm is not smart enough

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#123]
It is easy to create bubbles taller than their parent:

![image](https://user-images.githubusercontent.com/16720883/46444465-18a37500-c740-11e8-94f3-ccb1ce1767bc.png)

**Comment by mcwhitaker** [comment]
I wanted to add here a screenshot of how the Variations timeliner bubble heights allow for the labels of the bubbles to be shown given the height difference between the levels:

![image](https://user-images.githubusercontent.com/16720883/46554504-81a8fb00-c8ae-11e8-9707-fa8ee9cb6ea3.png)

Note how bubbles of the same level have about the same height regardless of how wide they are. I think this is what makes it possible to ensure that the parents do enclose their children.

![image](https://user-images.githubusercontent.com/16720883/46554787-5c68bc80-c8af-11e8-8b98-f61700a8331a.png)

**Comment by stephenwf** [comment]
Closing for now, further improvements can be recorded in a new ticket.
