### ISSUE TITLE
Can no longer add any bubbles

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#132]
I can no longer add bubbles. The ADD button is not available. This happens on firefox, edge, chrome. I have not tested anything with safari yet.

This is a screenshot to show the missing button, but it also shows an interesting layout issue on Edge, which is the bubble is upside down placed on top:

![image](https://user-images.githubusercontent.com/16720883/46500583-2ebd3e00-c7f1-11e8-95e1-c79b74c76416.png)

**Comment by adam-digirati** [comment]
The add button inserts a marker at the playhead position. This has been recently updated as per requested on the #129 issue. On the attached example, there is a marker at 00:00, therefore the add button is disabled.

The upside down bubbles in old Edge browsers fixed #143 pull request.

**Comment by mcwhitaker** [comment]
You are correct. Thank you!
