### ISSUE TITLE
Indication of playhead not clear enough

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#134]
In the Variations timeliner the playhead was a moving marker under the player scrubber:

![image](https://user-images.githubusercontent.com/16720883/46501166-b22b5f00-c7f2-11e8-9073-5b5e42184b5c.png)

This is one of the issues that may be left for phase 2.

**Comment by stephenwf** [comment]
<img width="58" alt="screen shot 2018-10-06 at 16 46 38" src="https://user-images.githubusercontent.com/8266711/46573046-71b11a00-c987-11e8-9eba-652ca2d3e2eb.png">

Indicator is a little mis-aligned for me @adam-digirati

**Comment by adam-digirati** [comment]
@stephenwf fixed in https://github.com/digirati-co-uk/timeliner/pull/156/files#diff-a57ce04a64f3b15ce04becd526c71e92
