### ISSUE TITLE
Grouping and grouped bubbles with wrong height when a saved project is uploaded

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#164]
This may be related to #123 but I mention it because it may also be part of the json reader logic.

I saved a project that looked like this:
![image](https://user-images.githubusercontent.com/16720883/46961233-56709980-d06e-11e8-8ca3-6d5db91469ff.png)

When I re-load the project, I get this:
![image](https://user-images.githubusercontent.com/16720883/46961293-786a1c00-d06e-11e8-83c2-245e4829e623.png)

This points to the fact that the groups of bubbles are not well recognized by the manifest reader -- the grouping bubble is shorter than the grouped bubbles and it should be the other way around.

Some colors still not carried over, but that is #159.

**Comment by stephenwf** [comment]
This has been marked as completed, closing for now.
