### ISSUE TITLE
You can remove all ranges in an empty project

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#171]
You can remove all the ranges from a project without range, including when you first load up the page as an empty page.

**Comment by adam-digirati** [comment]
@stephenwf example, please.

**Comment by stephenwf** [comment]
![empty-ranges](https://user-images.githubusercontent.com/8266711/47008022-5d141500-d131-11e8-8a14-b3e73386cdfc.gif)

**Comment by adam-digirati** [comment]
@stephenwf In your case, there was no audio file loaded. And you resetting the nothing. There are multiple ways to handle this...
A:
We can make the import screen permanent until no audio file is loaded (obviously with the cancel option disabled). This is the most sensible option at the moment IMHO.
B: 
We can set up disabled states for the top bar action buttons, in case of no audio.

**Comment by adam-digirati** [comment]
@stephenwf so I went for the first option, but we need to review it if we add the `?manifest=${manifest_url}` as a parameter to query string later on.
