### ISSUE TITLE
Ability to create a marker

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#190]
A marker, distinct from a bubble, is represented by a single point on the viewer. This ticket will cover the functionality of markers and also the UI for them.

A user should be able to:
* Add a new marker
* Delete an existing marker
* Move a marker
* Change a markers time-stamp with text input

Need clarification on this:
* When you skip to the "next bubble" should this include the markers so if theres a marker in the middle of a bubble, skipping from the start of that bubble will take you to the middle of the bubble where the marker is, and not the end of the bubble.

**Comment by villedigirati** [comment]
Skipping should be to next marker or timepoint
