### ISSUE TITLE
As a user, I can control the playback of the audio so that I can move to any point in the timeline

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#2]
**Acceptance Criteria**
* [ ] I can play the audio file
* [ ] I can pause the audio file
* [ ] I can scrub the audio file backwards
* [ ] I can scrub the audio file forwards
* [ ] I can skip to the next bubble point
* [ ] I can skip to the previous bubble point
* [ ] I can see the playhead moving accordingly along the timeline

**Dev tasks**
* [ todo ]

**Comment by villedigirati** [comment]
Jon Dunn asked if the time stamp part of the ui could be editable to allow precise advancement to a point in time https://preview.uxpin.com/874bd44d74fc6062565cd95dc2dfc9e694b6ed4f#/pages/92279172/comment/comments/5b96706fcf090410d0488f74

**Comment by stephenwf** [comment]
I think that would be interesting. Few notes on doing that:
- UX would be required from you to define that interaction (is it just plain text or is it a time picker of sorts)
- Dev challenge of taking a formatted string like `12:34:56` and converting it back into milliseconds.
- New UI components to reflect those changes

We did put the play head and timeline scrubber on hold as we knew there would be questions around its behaviours
