### ISSUE TITLE
Undo/Redo last action

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#201]
The ability to undo the last action. This can be done as many times as you want until you hit the last time you "saved". This may not be applicable to non-Avalon builds of the timeliner as the concept of saving is a download.

Users can also redo any undone actions.

**Comment by villedigirati** [comment]
Just a note here - we're experiencing some complexity and performance issues with this. Original request did only request undo (and in the context of adding/deleting bubbles). Just wonder if we need to look at the extent of this feature...

**Comment by villedigirati** [comment]
Just a note here - original request just requested an "undo" action - given we're experiencing performance issues, would it help if we did not have a "redo" state?

**Comment by stephenwf** [comment]
Not particularly for the problems I was running into, it was keeping track of the past that was causing the issues.

**Comment by stephenwf** [comment]
Updating with some work I've done today, the current status of undo:

**Works as expected**

* Updating manifest label
* Updating manifest summary
* Setting language (not in UI yet)
* Moving a time point
* Updating annotation

**Requires refactoring to work**

* Splitting ranges (adding bubbles)
* Grouping ranges
* Deleting ranges

**Could be implemented, but deprioritised**

* Site settings
* Bubble selections

**Comment by villedigirati** [comment]
Yeah the last 2 I wouldn't expect as a user.
Setting language?

**Comment by stephenwf** [comment]
Setting a language for the annotations and project metadata. It's in the data model, but not in the UI. Currently defaults to `en` and is used in the language maps in the IIIF output.

**Comment by stephenwf** [comment]
Now that makers are undo-able this is now complete
