### ISSUE TITLE
Provide feedback when input file or manifest is not supported

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#203]
Currently there is no user-friendly messaging when an incorrect resource is loaded into the first step of the viewer. There should be a better UX flow for handling different levels of "not supported". For example, trying to import a 404 resource should have different messaging to trying to import a IIIF manifest that has no audio sources. They are both incompatible, but for different reasons. 

In addition, we should allow users to "try again" incase it was simply a paste-error.

**Comment by villedigirati** [comment]
I think the wording of the error message still needs to be looked at - so translating into plain english as much as possible.
