### ISSUE TITLE
Bubble label should not be rendered in black if the colour is black

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#206]
Related to #173 

This makes the label completely invisible. This raises question over what counts as black. Should all very dark colours have their label colours switched?

**Comment by villedigirati** [comment]
Can we perform some sort of minimum contrast ratio check?

Or is a dark/light label toggle more useful/easy/solid?

**Comment by villedigirati** [comment]
Toggle agreed
