### ISSUE TITLE
Change UI shape for Timepoints and markers

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#239]
Current shapes too similar - try to emulate original

used vertical lines for timepoints
Triangles for markers

https://xd.adobe.com/spec/ef02311f-a16a-4671-6774-22e42a22d7be-9933/screen/dc07c9c7-5c69-4823-9762-e1af4132e33b/1280/

**Comment by stephenwf** [comment]
Vertical lines for the time-points are now in place.

**Comment by stephenwf** [comment]
![revision](https://user-images.githubusercontent.com/8266711/53929189-ce267b80-4084-11e9-8dff-1de3844c14e5.gif)
