### ISSUE TITLE
Merging bubbles

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#24]
There is a requirement to select more than one bubble and merge them, but some sets of bubbles can't be merged (say 2 children from different bubbles completely). We may need a set of rules on when its okay to merge bubbles and what will happen under different scenarios.

**Comment by mcwhitaker** [comment]
I would think that we would only be able to merge bubbles that are children of the same parent (thus, at the same level) and with no other bubbles in between them.

Given that the old timeliner does not have the concept of merging, for MVP this seems more than sufficient. @jwd -- agreed?
