### ISSUE TITLE
Add audio scrubber handle

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#240]
Use circle shape on the timeline as audio progresses

https://xd.adobe.com/spec/ef02311f-a16a-4671-6774-22e42a22d7be-9933/screen/dc07c9c7-5c69-4823-9762-e1af4132e33b/1280/

**Comment by stephenwf** [comment]
<img width="316" alt="screenshot 2019-03-07 at 02 57 11" src="https://user-images.githubusercontent.com/8266711/53929171-b9e27e80-4084-11e9-9c12-df16cab3240a.png">
