### ISSUE TITLE
Move marker below timeline

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#241]
If we could move them a little below the timeline/scrubber area, we can prevent conflicts between scrubbing and moving these markers.

See

https://xd.adobe.com/spec/ef02311f-a16a-4671-6774-22e42a22d7be-9933/screen/dc07c9c7-5c69-4823-9762-e1af4132e33b/1280/

**Comment by stephenwf** [comment]
![revision](https://user-images.githubusercontent.com/8266711/53929179-c535aa00-4084-11e9-8790-f6794519fc21.gif)
