### ISSUE TITLE
Double click bubble to edit properties

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#242]
This currently plays the audio. Changing the behaviour to this would allow more immediate editing, and probably would feel more intuitive.

**Comment by stephenwf** [comment]
I have implemented something similar to the markers:

![edit-marker](https://user-images.githubusercontent.com/8266711/53877358-dd63e580-4000-11e9-92e8-d1ca2fa9cb37.gif)

We could use this along side double clicking the bubbles.
