### ISSUE TITLE
Lighter default colour swatch

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#245]
Current set is too saturated.

UX to supply another swatch.

Suggested colours to throw in (less saturated I hope!)

#ACD4E2,
#A1F0C9,
#FFEE72,
#F4BCBA,
#D4F4EF

**Comment by stephenwf** [comment]
<img width="1209" alt="screenshot 2019-03-06 at 11 36 20" src="https://user-images.githubusercontent.com/8266711/53929134-a20afa80-4084-11e9-92dd-8a9c9ef9ad4d.png">
