### ISSUE TITLE
Improve "draggability" of timeline area

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#249]
Users cannot drag on the bubbles when zooming in. This is particularly a problem if you have tall/grouped bubbles.

We could perhaps make the action clearer by considering the mouse pointer shape on bubbles vs bg canvas area

**Comment by stephenwf** [comment]
This is done. To distinguish between a click and a drag the following rules are in place (timings can be tweaked)
* If the mouse is clicked down and then released in under 500ms its a click
* If the mouse is clicked down and not released after 500ms a drag is started
* If the mouse is clicked down and then moved more than 10 pixels, a drag is started

Once a drag is started, a click cannot be registered. The result is a tiny "sticking" when dragging, but with such small values its not noticeable and the only way to distinguish clicks from drags.
