### ISSUE TITLE
UX: Import screen tabs 

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#256]
See UX

https://xd.adobe.com/spec/ef02311f-a16a-4671-6774-22e42a22d7be-9933/screen/3786e5d9-1bb9-42c0-a058-cf4af506424b/Import-Dialogue/

Wording (add any supported formats)

Header: Open audio

"Open an audio file (.mp3, .json) from the web"

"Open an audio file on your computer (.mp3, .json)"

"Open a demo audio file to get you started"

**Comment by stephenwf** [comment]
The tab interface is done, the demo audio file is not done though. I've created a new ticket to track this in #266

**Comment by villedigirati** [comment]
Can you check the XD designs for design and wording - happy to go through if needs more focus on things to change.

**Comment by stephenwf** [comment]
<img width="445" alt="screenshot 2019-03-06 at 21 46 28" src="https://user-images.githubusercontent.com/8266711/53916141-555dfa00-4059-11e9-833d-7a05fe455e64.png">
<img width="442" alt="screenshot 2019-03-06 at 21 46 24" src="https://user-images.githubusercontent.com/8266711/53916143-555dfa00-4059-11e9-8444-ca477e0f9758.png">
