### ISSUE TITLE
Zoom to selection feature of the timeliner

### ISSUE THREAD

**Issue by srsridh** [digirati-co-uk/timeliner#263]
I tried to test this functionality in

https://deploy-preview-233--iiif-timeliner.netlify.com/
**Observation**:
From the statement of work - Zoom to selection  – as in the old timeliner,

"_If multiple bubbles are selected, the zoomed area goes from the beginning of the first bubble to the end of the last bubble_."

Also, when only one bubble was selected, only that bubble was not shown in the zoomed area 

So when tested, the above link **did not** function as expected

**Comment by stephenwf** [comment]
Hi @srsridh are you using the following link to test: https://deploy-preview-233--iiif-timeliner.netlify.com I just want to confirm as that the only place this behaviour is available at the moment.

The interaction won't work with single bubbles, as when you select a bubble it would immediately zoom in to the start and end of that bubble, stopping you from choosing a second without first zooming out. 

What part of the zoom to selection was not functioning as expected during your testing?

**Comment by srsridh** [comment]
Hi @stephenwf , sorry i had missed to include the link. I updated my comment now. Yes, i had tested in the same link

For multiple bubbles, this functionality was not working

**If multiple bubbles are selected, the zoomed area goes from the beginning of the first bubble to the end of the last bubble**

For a single bubble, now that you have mentioned selecting and zooming over it is automatically taking us to the last bubble and not the start and end of that bubble. Also, this is not constant. For the bubbles towards the end, it is working like you had mentioned (it would immediately zoom in to the start and end of that bubble)

**Comment by mcwhitaker** [comment]
I am sorry, I duplicated this ticket. #278 is the same thing. There is more clarification on that ticket.
