### ISSUE TITLE
Annotations Section Does Not Scroll in Firefox

### ISSUE THREAD

**Issue by joncameron** [digirati-co-uk/timeliner#268]
### Description
The "Annotations" area, if it contains more items than can be shown at once, scrolls vertically for me in Chrome and Safari but not in Firefox. Firefox does not display a scroll bar or scroll with a scroll event from my mouse.

### Environment
Firefox 65.0.1, macOS 10.14.3.

**Comment by stephenwf** [comment]
Interesting, I was able to replicate the bug. It looks like the height is going past the bottom of the page. I think it might be a flex-box issue, will check it out!
