### ISSUE TITLE
Zooming in to the last bubble when not requested

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#269]
After zooming in a bubble and then zooming out, clicking on the last it zooms into that bubble, but just the end of that bubble is on screen.

![bug1](https://user-images.githubusercontent.com/16720883/54162616-7b561680-442c-11e9-92ee-2ec62add8463.gif)

Clicking on the last bubble should only select that bubble, nothing else.

**Comment by stephenwf** [comment]
Ah I've been trying to replicate this one so I can add a test, I've seen it pop up a few times but never figured out what had happened. thanks!

**Comment by mcwhitaker** [comment]
If I remember correctly, it only happens if I wait a little before clicking on that last bubble.

**Comment by mcwhitaker** [comment]
@stephenwf  This is happening under different conditions. I have had it happen to me when creating a marker a couple of times. I even have a recording of it because I was trying to record a 3-minute demo but I can upload an mp4 to github. I will email it.

**Comment by mcwhitaker** [comment]
A simpler example of when this happens. In this case, the timeline disappears altogether and there is no way to recover. Under the conditions reported before, we could recover.

![bug3](https://user-images.githubusercontent.com/16720883/54386473-67e6bd80-466f-11e9-9437-f6eb1427956e.gif)
