### ISSUE TITLE
Selecting 2 bubbles to group them is zooming in

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#278]
We are supposed to zoom in only the user requests it by clicking on the correct icon/gadget/button.

**Comment by villedigirati** [comment]
The SoW specified this behaviour, unless it was misunderstood by us:
"Zoom to selection – as it works in the old timeliner. If multiple bubbles are selected, the zoomed area goes from the beginning of the first bubble to the end of the last bubble."

and we had a ticket for this before:

https://github.com/digirati-co-uk/timeliner/issues/195

**Comment by mcwhitaker** [comment]
Yes, I can see why the confusion. What I meant was that the zoom feature would not just zoom in x%, it would zoom to the selected bubbles. My assumption that _as it works in the old timeliner_ was understandable was not a good assumption. Sorry about that.

**Comment by villedigirati** [comment]
Ok so zooming must always be activated implicitly by using the zoom controls, but selecting multiple bubbles will constrain the zoomable area to those bubbles.

**Comment by mcwhitaker** [comment]
I think you meant explicitly in your comment above. Yes, explicitly.

**Comment by villedigirati** [comment]
Yes sorry! Doh!

**Comment by cjcolvar** [comment]
@mcwhitaker We've fixed this locally in our fork.

**Comment by stephenwf** [comment]
Hi @cjcolvar removing the saga will not fix the initial requirement of this behaviour when clicking on the "zoom in" button

**Comment by cjcolvar** [comment]
@stephenwf @mcwhitaker I see that I didn't read the full issue thread.  To be clear, I agree that that PR does not add the requested behavior of zoom to selection, but it does fix the original issue of zooming when selecting multiple bubbles.
