### ISSUE TITLE
Player should not play beyond the end of the media fragment

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#286]
When the timeline is limited to a fragment of the audio file via the t=x,y parameter, the player should be limited by X and Y and not play anything before time point X or after time point Y.

In the meeting on 3/13 we showed that the player did not stop when reaching the end of the media fragment (time point Y).

**Comment by cjcolvar** [comment]
@mcwhitaker We've fixed this locally in our fork.
