### ISSUE TITLE
White Label control is changing the custom color of the bubble back to its level color in the current scheme 

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#287]
When a bubble has a custom color and one uses the _White Label Colour_ control, the bubble color is changed back to the color assigned for its level in the current color scheme for the timeline.

![white-label](https://user-images.githubusercontent.com/16720883/54456307-371c8c00-4734-11e9-831c-a169141b2e40.gif)

Also, to avoid dispute about the correct spelling of _color/colour_, maybe remove the word altogether from this control label? :-)

**Comment by mcwhitaker** [comment]
Just noticed ticket #272 . I think this one here is more specific about when that occurs. I have not seen this happen when the bubble color is not custom.

**Comment by cjcolvar** [comment]
I think this is related #288.
