### ISSUE TITLE
Color scheme reverted to default upon naming a marker

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#288]
I started with a manifest stored locally for which the color scheme was the Bright colors.

The flipping back to the default color scheme only occurred when, after deleting a marker, I added a new one. 

![marker-color-scheme](https://user-images.githubusercontent.com/16720883/54463644-29720100-474a-11e9-8b81-96efbe43604c.gif)

Also, if I visited the settings popup before doing anything, following the same steps did not flip the colors to the default color scheme even if I simply escaped out of the popup or cancelled out.

**Comment by mcwhitaker** [comment]
When testing some other things, I found that the same issue of reverting to the default color scheme would happen if I simply manually change the time value of any of the end points. 

Again, this is when I upload a manifest that uses a color scheme other than the default one. I think something is not being set that gets set when I visit the settings page.

**Comment by stephenwf** [comment]
Oh that is a strange issue! Yes I think it must not be being saved somewhere.

**Comment by cjcolvar** [comment]
I'm seeing a similar bug with this scenario:
- Edit a bubble and choose a custom color and save
- Edit the bubble again and change the title and save
- Notice the bubble color reverts

**Comment by stephenwf** [comment]
Cannot replicate on master

**Comment by cjcolvar** [comment]
@stephenwf I'm still able to replicate this on https://master--iiif-timeliner.netlify.com/ with these steps:
1) Click edit pencil for a bubble annotation
2) Select a custom color
3) Click Save
4) Click edit pencil for the same bubble annotation
5) Edit the label
6) Click Save
The color reverts to the palette on the second save.

**Comment by stephenwf** [comment]
Thanks @cjcolvar that's my mistake, its fixed now here: https://github.com/digirati-co-uk/timeliner/pull/302
