### ISSUE TITLE
Unable to use audio from a video file

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#290]
Please see #185, marked as done. I have been unable to load an mp4 file to validate this.

**Comment by stephenwf** [comment]
Hi @mcwhitaker I've tested with a few MP4s and M4V video files without issue. Would it be possible to know the link you were having trouble with?

Also can you test with these two files:
https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4
https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_640x360.m4v

And let me know if they work for you?

**Comment by mcwhitaker** [comment]
@stephenwf  - you are right. This was user error.
