### ISSUE TITLE
As a user, I want to be able to see and create labels and descriptions for the bubbles that I have created.

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#9]
**Acceptance criteria**
* [ ] I can add label to bubble
* [ ] I can add summary to bubble
* [ ] I can edit an existing label
* [ ] I can edit and existing summary

**Dev tasks**
* [ todo ]

**Comment by mcwhitaker** [comment]
Will this enable editing as well?

**Comment by mcwhitaker** [comment]
Sorry, I did not think of this yesterday, but maybe add "delete" as well? If we make the assumption that everything one can create/add, one can also edit and delete, I am fine with not being explicit about this. For instance, story #4 talks about adding the bubbles and stories #5 and #10 talk about changes to the bubbles, but we don't have a story that includes the ability to delete them.

**Comment by mcwhitaker** [comment]
A separate story for the deletion is a good idea, Stephen. Yes, we should clarify those scenarios. The people who would know best the use cases here would be Jon Dunn and Phil Ponella and I can make sure we get that clarification.
